export const stationsData = [
    {
        id: "S1",
        location: "Colombo City",
        latitude: 6.9271,
        longitude: 79.8612,
        chargers: [
            { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C02", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C03", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
            { id: "C06", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C07", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C08", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C09", status: "In Use", chargerType: "FC-SP", power: 40 },
            { id: "C10", status: "Available", chargerType: "FC-SP", power: 35 },
            { id: "C11", status: "Available", chargerType: "FC-SP", power: 55 },
            { id: "C12", status: "Available", chargerType: "FC-SP", power: 40 },
            { id: "C13", status: "In Use", chargerType: "FC-SP", power: 30 },
            { id: "C14", status: "Available", chargerType: "FC-SP", power: 35 },
            { id: "C15", status: "Available", chargerType: "FC-SP", power: 75 },
            { id: "C16", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C17", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C18", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C19", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C20", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C21", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C22", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C23", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C24", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C25", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C26", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C27", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C28", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C29", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C30", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C31", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C32", status: "Available", chargerType: "L2-HC", power: 6.6 },
            { id: "C33", status: "In Use", chargerType: "L2-HC", power: 3.3 },
            { id: "C34", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C35", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C36", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C37", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C38", status: "Available", chargerType: "L2-3P", power: 15 },
            { id: "C39", status: "In Use", chargerType: "L2-3P", power: 7 },
            { id: "C40", status: "Available", chargerType: "L2-3P", power: 22 }
        ],
        totalChargers: 40,
        powerRating: 75,
        solarPV: 350,
        storagesolarpower: 500,
        maxFeederCapacity: 300,
        internet: "Stable",
        peakDemand: 480,
        gridDraw: 300,
        gridOffsetPercent: 70
    },
    {
        id: "S2",
        location: "Kandy",
        latitude: 7.2906,
        longitude: 80.6337,
        chargers: [
            { id: "C01", status: "Available", chargerType: "L2-HC", power: 6.6 },
            { id: "C02", status: "In Use", chargerType: "L2-HC", power: 3.3 },
            { id: "C03", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
            { id: "C06", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C07", status: "Available", chargerType: "FC-SP", power: 75 },
            { id: "C08", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C09", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C10", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C11", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C12", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C13", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C14", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C15", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C16", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C17", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C18", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C19", status: "Available", chargerType: "L2-3P", power: 7 },
            { id: "C20", status: "In Use", chargerType: "L2-3P", power: 7 }
        ],
        totalChargers: 20,
        powerRating: 6.6,
        solarPV: 180,
        storagesolarpower: 200,
        maxFeederCapacity: 150,
        internet: "Stable",
        peakDemand: 132,
        gridDraw: 150,
        gridOffsetPercent: 62
    },
    {
        id: "S3",
        location: "Galle",
        latitude: 6.0535,
        longitude: 80.2210,
        chargers: [
            { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C02", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C03", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
            { id: "C06", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C07", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C08", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C09", status: "In Use", chargerType: "FC-SP", power: 40 },
            { id: "C10", status: "Available", chargerType: "FC-SP", power: 35 },
            { id: "C11", status: "Available", chargerType: "FC-SP", power: 55 },
            { id: "C12", status: "Available", chargerType: "FC-SP", power: 40 },
            { id: "C13", status: "In Use", chargerType: "FC-SP", power: 30 },
            { id: "C14", status: "Available", chargerType: "FC-SP", power: 35 },
            { id: "C15", status: "Available", chargerType: "FC-SP", power: 75 },
            { id: "C16", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C17", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C18", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C19", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C20", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C21", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C22", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C23", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C24", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C25", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C26", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C27", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C28", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C29", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C30", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C31", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C32", status: "Available", chargerType: "L2-HC", power: 6.6 },
            { id: "C33", status: "In Use", chargerType: "L2-HC", power: 3.3 },
            { id: "C34", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C35", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C36", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C37", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C38", status: "Available", chargerType: "L2-3P", power: 7 },
            { id: "C39", status: "In Use", chargerType: "L2-3P", power: 7 },
            { id: "C40", status: "Available", chargerType: "L2-3P", power: 22 }
        ],
        totalChargers: 40,
        powerRating: 75,
        solarPV: 300,
        storagesolarpower: 400,
        maxFeederCapacity: 200,
        internet: "Stable",
        peakDemand: 480,
        gridDraw: 200,
        gridOffsetPercent: 65
    },
    {
        id: "S4",
        location: "Negombo",
        latitude: 7.2088,
        longitude: 79.8359,
        chargers: [
            { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C02", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C03", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C05", status: "Available", chargerType: "FC-SP", power: 55 },
            { id: "C06", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C07", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C08", status: "Available", chargerType: "FC-SP", power: 45 },
            { id: "C09", status: "In Use", chargerType: "FC-SP", power: 40 },
            { id: "C10", status: "Available", chargerType: "FC-SP", power: 35 },
            { id: "C11", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C12", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C13", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C14", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C15", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C16", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C17", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C18", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C19", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C20", status: "Available", chargerType: "FC-DP", power: 60 },
            { id: "C21", status: "In Use", chargerType: "L2-HC", power: 6.6 },
            { id: "C22", status: "Available", chargerType: "L2-HC", power: 3.3 },
            { id: "C23", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C24", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C25", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C26", status: "In Use", chargerType: "L2-3P", power: 11 },
            { id: "C27", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C28", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C29", status: "Available", chargerType: "L2-3P", power: 11 },
            { id: "C30", status: "Available", chargerType: "L2-3P", power: 11 }
        ],
        totalChargers: 30,
        powerRating: 75,
        solarPV: 200,
        storagesolarpower: 300,
        maxFeederCapacity: 150,
        internet: "Stable",
        peakDemand: 600,
        gridDraw: 150,
        gridOffsetPercent: 65
    },
    {
        id: "S5",
        location: "Ratnapura",
        latitude: 6.6828,
        longitude: 80.3992,
        chargers: [
            { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C02", status: "In Use", chargerType: "FC-DP", power: 60 },
            { id: "C03", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C04", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C05", status: "In Use", chargerType: "L2-3P", power: 10 },
            { id: "C06", status: "Available", chargerType: "L2-3P", power: 15 },
            { id: "C07", status: "Available", chargerType: "L2-3P", power: 20 },
            { id: "C08", status: "Available", chargerType: "L2-HC", power: 6.6 },
        ],
        totalChargers: 8,
        powerRating: 22,
        solarPV: 200,
        storagesolarpower: 150,
        maxFeederCapacity: 112,
        internet: "Stable",
        peakDemand: 176,
        gridDraw: 112,
        gridOffsetPercent: 36
    },
    {
        id: "S6",
        location: "Kurunegala",
        latitude: 7.4818,
        longitude: 80.3609,
        chargers: [
            { id: "C01", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C02", status: "In Use", chargerType: "FC-DP", power: 75 },
            { id: "C03", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C05", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C06", status: "In Use", chargerType: "FC-DP", power: 75 },
            { id: "C07", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C08", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C09", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C10", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C11", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C12", status: "In Use", chargerType: "FC-DP", power: 75 },
        ],
        totalChargers: 12,
        powerRating: 75,
        solarPV: 200,
        storagesolarpower: 250,
        maxFeederCapacity: 150,
        internet: "Stable",
        peakDemand: 600,
        gridDraw: 150,
        gridOffsetPercent: 60
    },
    {
        id: "S7",
        location: "Anuradhapura",
        latitude: 8.3114,
        longitude: 80.4037,
        chargers: [
            { id: "C01", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C02", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C03", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C04", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C05", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C06", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C07", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C08", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C09", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C10", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C11", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C12", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C13", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C14", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C15", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C16", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C17", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C18", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C19", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C20", status: "In Use", chargerType: "L2-3P", power: 22 },
        ],
        totalChargers: 20,
        powerRating: 22,
        solarPV: 200,
        storagesolarpower: 200,
        maxFeederCapacity: 100,
        internet: "Stable",
        peakDemand: 220,
        gridDraw: 100,
        gridOffsetPercent: 55
    },
    {
        id: "S8",
        location: "Jaffna",
        latitude: 9.6615,
        longitude: 80.0255,
        chargers: [
            { id: "C01", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C02", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C03", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "In Use", chargerType: "FC-DP", power: 75 },
            { id: "C05", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C06", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C07", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C08", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C09", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C10", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C11", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C12", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C13", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C14", status: "In Use", chargerType: "FC-DP", power: 75 },
            { id: "C15", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C16", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C17", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C18", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C19", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C20", status: "In Use", chargerType: "FC-DP", power: 75 },
        ],
        totalChargers: 20,
        powerRating: 75,
        solarPV: 300,
        storagesolarpower: 500,
        maxFeederCapacity: 250,
        internet: "Stable",
        peakDemand: 800,
        gridDraw: 250,
        gridOffsetPercent: 65
    },
    {
        id: "S9",
        location: "Matara",
        latitude: 5.9549,
        longitude: 80.5550,
        chargers: [
            { id: "C01", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C02", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C03", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C04", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C05", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C06", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C07", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C08", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C09", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C10", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C11", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C12", status: "In Use", chargerType: "FC-SP", power: 50 },
            { id: "C13", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C14", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C15", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C16", status: "Available", chargerType: "FC-SP", power: 50 },
            { id: "C17", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C18", status: "Available", chargerType: "FC-DP", power: 75 },
            { id: "C19", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C20", status: "Available", chargerType: "L2-3P", power: 22 },
        ],
        totalChargers: 20,
        powerRating: 50,
        solarPV: 300,
        storagesolarpower: 350,
        maxFeederCapacity: 200,
        internet: "Stable",
        peakDemand: 480,
        gridDraw: 200,
        gridOffsetPercent: 60
    },
    {
        id: "S10",
        location: "Badulla",
        latitude: 6.9897,
        longitude: 81.0561,
        chargers: [
            { id: "C01", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C02", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C03", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C04", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C05", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C06", status: "In Use", chargerType: "L2-3P", power: 22 },
            { id: "C07", status: "Available", chargerType: "L2-3P", power: 22 },
            { id: "C08", status: "Available", chargerType: "L2-3P", power: 22 },
        ],
        totalChargers: 8,
        powerRating: 22,
        solarPV: 80,
        storagesolarpower: 120,
        maxFeederCapacity: 150,
        internet: "Stable",
        peakDemand: 176,
        gridDraw: 150,
        gridOffsetPercent: 50
    }
];
